FROM node:latest

ENV NODE_ENV=production

WORKDIR /var/www/sltech/

COPY package-lock.json /var/www/sltech/
COPY package.json /var/www/sltech/

RUN npm ci

COPY infra/dist/server/ /var/www/sltech/
COPY infra/dist/www/index.html /var/www/sltech/index.html

CMD [ "node", "main.mjs" ]
