FROM node:latest

ENV NODE_ENV=production

COPY infra/dist/www/ /var/www/sltech/
COPY package-lock.json /var/www/sltech/
COPY package.json /var/www/sltech/

WORKDIR /var/www/sltech/

RUN npm ci

CMD [ "node", "server/main.js" ]
