import './realms.css';

export const CONF = {
    theme: "realms",
    useLanding: false,
    briqMaterials: ["0x2"],
    defaultMaterial: "0x2",
    builderSettings: {
        darkMode: {
            planeColor: "#161619",
            gridColor: "#8d795b",
            backgroundColor: "#929090",
        },
        lightMode: {
            planeColor: "#161619",
            gridColor: "#8d795b",
            backgroundColor: "#929090",    
        }
    },
    defaultPalette: {
        '#ffffff': 'Platinum',
        '#cdcdcd': 'Silver A',
        '#aaa9a9': 'Silver B',
        '#adadad': 'Stone A',
        '#c4c4c4': 'Stone B',
        '#313131': 'Coal A',
        '#171717': 'Coal B',
        '#623500': 'Wood A',
        '#794200': 'Wood B',
        '#f0af19': 'Gold A',
        '#e59e1a': 'Gold B',
        '#d44c28': 'Copper A',
        '#e86034': 'Copper B',
    }
}

export const defaultModel: { "pos": [number, number, number], "color": string }[] = [
    {"pos":[-6,0,0], "color":"#ffffff"},
    {"pos":[-7,1,0], "color":"#ffffff"},
    {"pos":[-7,2,0], "color":"#ffffff"},
    {"pos":[-5,0,0], "color":"#ffffff"},
    {"pos":[-5,6,0], "color":"#ffffff"},
    {"pos":[-5,7,0], "color":"#ffffff"},
    {"pos":[-4,0,0], "color":"#ffffff"},
    {"pos":[-4,5,0], "color":"#ffffff"},
    {"pos":[-4,8,0], "color":"#ffffff"},
    {"pos":[-3,0,0], "color":"#ffffff"},
    {"pos":[-3,4,0], "color":"#ffffff"},
    {"pos":[-3,9,0], "color":"#ffffff"},
    {"pos":[-2,9,0], "color":"#ffffff"},
    {"pos":[-2,8,0], "color":"#ffffff"},
    {"pos":[-2,7,0], "color":"#ffffff"},
    {"pos":[-2,6,0], "color":"#ffffff"},
    {"pos":[-2,5,0], "color":"#ffffff"},
    {"pos":[-2,4,0], "color":"#ffffff"},
    {"pos":[-2,3,0], "color":"#ffffff"},
    {"pos":[-2,2,0], "color":"#ffffff"},
    {"pos":[-2,1,0], "color":"#ffffff"},
    {"pos":[-2,0,0], "color":"#ffffff"},
    {"pos":[4,0,0],"color":"#ffffff"},
    {"pos":[3,0,0],"color":"#ffffff"},
    {"pos":[2,0,0],"color":"#ffffff"},
    {"pos":[1,0,0],"color":"#ffffff"},
    {"pos":[1,1,0],"color":"#ffffff"},
    {"pos":[1,2,0],"color":"#ffffff"},
    {"pos":[1,3,0],"color":"#ffffff"},
    {"pos":[1,4,0],"color":"#ffffff"},
    {"pos":[1,5,0],"color":"#ffffff"},
    {"pos":[1,6,0],"color":"#ffffff"},
    {"pos":[1,7,0],"color":"#ffffff"},
    {"pos":[1,8,0],"color":"#ffffff"},
    {"pos":[2,4,0],"color":"#ffffff"},
    {"pos":[3,5,0],"color":"#ffffff"},
    {"pos":[4,6,0],"color":"#ffffff"},
    {"pos":[4,7,0],"color":"#ffffff"},
    {"pos":[3,8,0],"color":"#ffffff"},
    {"pos":[2,9,0],"color":"#ffffff"},
    {"pos":[1,9,0],"color":"#ffffff"},
    {"pos":[5,0,0],"color":"#ffffff"},
    {"pos":[6,1,0],"color":"#ffffff"},
    {"pos":[6,2,0],"color":"#ffffff"},
    {"pos":[1,10,0],"color":"#ffffff"},
    {"pos":[0,10,0],"color":"#ffffff"},
    {"pos":[2,11,0],"color":"#ffffff"},
    {"pos":[0,11,0],"color":"#ffffff"},
    {"pos":[-1,10,0],"color":"#ffffff"},
    {"pos":[-1,11,0],"color":"#ffffff"},
    {"pos":[-2,10,0],"color":"#ffffff"},
    {"pos":[-3,11,0],"color":"#ffffff"}
];

export * as RealmsLogo from '@/assets/Realms.svg';
