import './realms.css';

export const CONF = {
    theme: "realms",
    useLanding: false,
    briqMaterials: ["0x2"],
    defaultMaterial: "0x2",
    builderSettings: {
        darkMode: {
            planeColor: "#161619",
            gridColor: "#8d795b",
            backgroundColor: "#929090",
        },
        lightMode: {
            planeColor: "#161619",
            gridColor: "#8d795b",
            backgroundColor: "#929090",    
        }
    },
    defaultPalette: {
        '#1e3a8a': 'Adamantine',
        '#bdbdbd': 'Alchemical Silver',
        '#757575': 'Coal',
        '#fca5a5': 'Cold Iron',
        '#f59e0b': 'Copper',
        '#93c5fd': 'Deep Crystal',
        '#ccbcfb': 'Diamonds',
        '#ec4899': 'Dragonhide',
        '#10b981': 'Ethereal Silica',
        '#fcd34d': 'Gold',
        '#fca5a4': 'Hartwood',
        '#ef4444': 'Ignium',
        '#b91c1c': 'Ironwood',
        '#60a5fa': 'Mithral',
        '#000000': 'Obsidian',
        '#dc2626': 'Ruby',
        '#3b82f6': 'Sapphire',
        '#eeeeee': 'Silver',
        '#e0e0e0': 'Stone',
        '#ffffff': 'True Ice',
        '#6d28d9': 'Twilight Quartz',
        '#78350f': 'Wood',
    }
}

export const defaultModel: { "pos": [number, number, number], "color": string }[] = [
    {"pos":[-6,0,0], "color":"#ffffff"},
    {"pos":[-7,1,0], "color":"#ffffff"},
    {"pos":[-7,2,0], "color":"#ffffff"},
    {"pos":[-5,0,0], "color":"#ffffff"},
    {"pos":[-5,6,0], "color":"#ffffff"},
    {"pos":[-5,7,0], "color":"#ffffff"},
    {"pos":[-4,0,0], "color":"#ffffff"},
    {"pos":[-4,5,0], "color":"#ffffff"},
    {"pos":[-4,8,0], "color":"#ffffff"},
    {"pos":[-3,0,0], "color":"#ffffff"},
    {"pos":[-3,4,0], "color":"#ffffff"},
    {"pos":[-3,9,0], "color":"#ffffff"},
    {"pos":[-2,9,0], "color":"#ffffff"},
    {"pos":[-2,8,0], "color":"#ffffff"},
    {"pos":[-2,7,0], "color":"#ffffff"},
    {"pos":[-2,6,0], "color":"#ffffff"},
    {"pos":[-2,5,0], "color":"#ffffff"},
    {"pos":[-2,4,0], "color":"#ffffff"},
    {"pos":[-2,3,0], "color":"#ffffff"},
    {"pos":[-2,2,0], "color":"#ffffff"},
    {"pos":[-2,1,0], "color":"#ffffff"},
    {"pos":[-2,0,0], "color":"#ffffff"},
    {"pos":[4,0,0],"color":"#ffffff"},
    {"pos":[3,0,0],"color":"#ffffff"},
    {"pos":[2,0,0],"color":"#ffffff"},
    {"pos":[1,0,0],"color":"#ffffff"},
    {"pos":[1,1,0],"color":"#ffffff"},
    {"pos":[1,2,0],"color":"#ffffff"},
    {"pos":[1,3,0],"color":"#ffffff"},
    {"pos":[1,4,0],"color":"#ffffff"},
    {"pos":[1,5,0],"color":"#ffffff"},
    {"pos":[1,6,0],"color":"#ffffff"},
    {"pos":[1,7,0],"color":"#ffffff"},
    {"pos":[1,8,0],"color":"#ffffff"},
    {"pos":[2,4,0],"color":"#ffffff"},
    {"pos":[3,5,0],"color":"#ffffff"},
    {"pos":[4,6,0],"color":"#ffffff"},
    {"pos":[4,7,0],"color":"#ffffff"},
    {"pos":[3,8,0],"color":"#ffffff"},
    {"pos":[2,9,0],"color":"#ffffff"},
    {"pos":[1,9,0],"color":"#ffffff"},
    {"pos":[5,0,0],"color":"#ffffff"},
    {"pos":[6,1,0],"color":"#ffffff"},
    {"pos":[6,2,0],"color":"#ffffff"},
    {"pos":[1,10,0],"color":"#ffffff"},
    {"pos":[0,10,0],"color":"#ffffff"},
    {"pos":[2,11,0],"color":"#ffffff"},
    {"pos":[0,11,0],"color":"#ffffff"},
    {"pos":[-1,10,0],"color":"#ffffff"},
    {"pos":[-1,11,0],"color":"#ffffff"},
    {"pos":[-2,10,0],"color":"#ffffff"},
    {"pos":[-3,11,0],"color":"#ffffff"}
];

export * as RealmsLogo from '@/assets/Realms.svg';
